# Generated by Django 5.1.2 on 2024-11-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tast_tracker', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
